Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Load Balancer
  config.vm.define "k3s-lb" do |lb|
    lb.vm.hostname = "k3s-lb"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Master Nodes
  (1..3).each do |i|
    config.vm.define "k3s-master-#{i}" do |master|
      master.vm.hostname = "k3s-master-#{i}"
      master.vm.network "private_network", ip: "192.168.56.1#{i}"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end

  # Worker Nodes
  (1..3).each do |i|
    config.vm.define "k3s-worker-#{i}" do |worker|
      worker.vm.hostname = "k3s-worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.56.2#{i}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  end
end
