apiVersion: v1
kind: Pod
metadata:
  name: pod-on-worker-1a
spec:
  nodeName: k3s-worker-1
  containers:
  - name: utils
    image: busybox:latest
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-on-worker-1b
spec:
  nodeName: k3s-worker-1
  containers:
  - name: utils
    image: busybox:latest
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-on-worker-2
spec:
  nodeName: k3s-worker-2
  containers:
  - name: utils
    image: busybox:latest
    command: ["sleep", "3600"]
